### ISSUE TITLE
Duplicated content in eventing-kafka-post-install.yaml on release page

### ISSUE THREAD

**Issue by tikr7** [knative-extensions/eventing-kafka-broker#3316]
All `eventing-kafka-post-install.yaml` on the [release page](eventing-kafka-post-install.yaml) (since version >1.4.3) have the content duplicated. So e.g. lines 1-479 equal lines 480-960. It leads to an issue while using terraform.

So if is just a little bug in GitHub Actions, would be glad to get that small thing fixed :)

**Comment by pierDipi** [comment]
Thanks for reporting @tikr7, this is the script that does the release and YAML manifest bundling https://github.com/knative-extensions/eventing-kafka-broker/blob/main/hack/release.sh, any help would be appreciated

**Comment by pierDipi** [comment]
@tikr7 do you know if it is not the case on more recent versions?

**Comment by tikr7** [comment]
Yes, its the case in all recent versions. Even the [most recent](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.11.3/eventing-kafka-post-install.yaml) one.

I was already looking into it but was not able to find the problem.

**Comment by tikr7** [comment]
@pierDipi 
Maybe because [line26](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/hack/control-plane.sh#L26) and [line30](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/hack/artifacts-env.sh) are duplicated?

**Comment by pierDipi** [comment]
I think that is the problem because we call those functions and they are appending the content
- https://github.com/knative-extensions/eventing-kafka-broker/blob/1e369784b4161dfb9a35eabe96b0db618991213b/hack/release.sh#L47
- https://github.com/knative-extensions/eventing-kafka-broker/blob/1e369784b4161dfb9a35eabe96b0db618991213b/hack/release.sh#L57

I think the best way to fix it is to avoid using `>>` (append) and use `>` (overwrite) on lines 26 and 30

**Comment by tikr7** [comment]
@pierDipi yes, I think you are right. I created an [PR](https://github.com/knative-extensions/eventing-kafka-broker/pull/3506).
Hopyfully it finds its way into the next release.
