### ISSUE TITLE
Eventing TLS: Test KafkaSource with a TLS sink

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#3409]
**Problem**

We should test KafkaSource with an eventshub TLS sink (implemented here https://github.com/knative/eventing/issues/6842)

A similar test to https://github.com/knative-extensions/eventing-kafka-broker/blob/5a7a83f7efa1255d4167f5edaf28f9dda2d68052/test/e2e_new/kafka_source_test.go#L103-L116

but the sink of the source should be eventshub enforcing TLS

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
3

**Additional context (optional)**

- we should use the feature implemented here https://github.com/knative/eventing/issues/6842

/help

**Comment by Rahul-Kumar-prog** [comment]
@pierDipi can you tell me about this` but the sink of the source should be eventshub enforcing TLS` ? what that mean

**Comment by Leo6Leo** [comment]
@Rahul-Kumar-prog Hey Rahul, I hope the code [here](https://github.com/Leo6Leo/eventing-kafka-broker/blob/c614e9860b68600fa54f7250ff9678641a540a86/test/rekt/features/broker_tls.go#L72) helped answer your question.

Are there anything else we could help you with on this issue?

**Comment by Leo6Leo** [comment]
Hey @Rahul-Kumar-prog! I hope you're doing well! We've noticed that there hasn't been much activity on this issue recently and we've missed your input. We just wanted to check in and see if everything is okay!

I understand that life gets busy and priorities can shift. If you have already starting tackling this issue, that's great! Please let us know if you need any support. However, if you're tied up with other commitments, no worries at all - just give us a heads-up so we can release this issue to others who are eager to contribute too!

Please let me know by commenting here within next 24 hours, otherwise I will be releasing this issue!

**Comment by Leo6Leo** [comment]
Hey @Rahul-Kumar-prog ! As I didn't hear back from you in the past 24 hour, I will un-assign this issue from you for now to leave the opportunity open for other contributors. Feel free to pick it up again if it hasn't been picked up and you have time to work on it!  :)))

**Comment by Rahul-Kumar-prog** [comment]
@Leo6Leo apology, I have not being active from a while in the knative community. because past few months my life goes very ups and downs.
specially my health so that why I am not active anywhere. 
I start working and connecting to the community as soon as I can. if anyone wants to work on this issue then its ok other wise you can assign again to me. its totally upto you.

**Comment by pierDipi** [comment]
@gunishmatta I'm adding the test for this feature as part of this PR https://github.com/knative-extensions/eventing-kafka-broker/pull/3605, feel free to review the PR
