### ISSUE TITLE
[control-plane]: Support exposing the Audience of a Broker

### ISSUE THREAD

**Issue by creydr** [knative-extensions/eventing-kafka-broker#3520]
As the [Eventing OIDC feature track](https://docs.google.com/document/d/1e7UgNTkL0Br5Da09Rg2ieVmhKJo4VXuBj-mHT9NCujY/edit#heading=h.glanb1rq6iu5) describes, Addressables (and thus Brokers) need to announce their audience in `.status.address.audience`.

In particular the EKB broker controller should:

* when the feature flag (see https://github.com/knative/eventing/issues/7174) is disabled:
  * no change in behavior
* when the feature flag (see https://github.com/knative/eventing/issues/7174) is enabled:
  * Set the Brokers `.status.address.audience` accordingly.

Additional Information:
* In eventing-core we have a helper function to create the audience string so the follow the same pattern: https://github.com/knative/eventing/blob/1e84b2e5328017d34e8c0c8e4ddd84da67381526/pkg/auth/audience.go#L28-L32 and its usage in https://github.com/knative/eventing/blob/1e84b2e5328017d34e8c0c8e4ddd84da67381526/pkg/reconciler/broker/broker.go#L242-L249

**Comment by gunishmatta** [comment]
@creydr  I would like to work on this.

**Comment by creydr** [comment]
> @creydr I would like to work on this.

Awesome. Just assign it to you via `/assign` if you want to work on it and make sure you've gone through [DEVELOPMENT.md](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/DEVELOPMENT.md) as this contains helpful information on how to getting started.

**Comment by Cali0707** [comment]
/triage accepted

/assign @gunishmatta 

Thanks for picking this up @gunishmatta :tada:

**Comment by Leo6Leo** [comment]
@gunishmatta 
Hey Gunish, are there anything we can help you with on this issue?

**Comment by Leo6Leo** [comment]
Hey @gunishmatta ! I hope you're doing well! We've noticed that there hasn't been much activity on this issue recently and we've missed your input. We just wanted to check in and see if everything is okay!

I understand that life gets busy and priorities can shift. If you have already starting tackling this issue, that's great! Please let us know if you need any support. However, if you're tied up with other commitments, no worries at all - just give us a heads-up so we can release this issue to others who are eager to contribute too!

Please let me know by commenting here within next 24 hours, otherwise I will be releasing this issue!

**Comment by gunishmatta** [comment]
Hi @Leo6Leo really sorry, got busy due to work commitments, I will raise a PR by this weekend. 

If this needs to be done before that then you can release this, else I will do
Thanks

**Comment by Leo6Leo** [comment]
Hey @gunishmatta  No problem! Take you time. Looking forward to your PR! Don't hesitate to Let us know if you have any questions, and we are here to help :))
