### ISSUE TITLE
knativekafkapartition CE extension does not conform to spec

### ISSUE THREAD

**Issue by cchayka-campsci** [knative-extensions/eventing-kafka-broker#3992]
**Describe the bug**
The CE Extension `knativekafkapartition` was recently added, but it does not conform to the CloudEvent spec.

https://github.com/knative-extensions/eventing-kafka-broker/pull/3464

`CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.`

With the NodeJS library in particular, it throws an error because "knativekafkapartition" is 21 characters.

Could it be changed to "knkafkapartition" possibly? (and probably "knativekafkaoffset" to "knkafkaoffset" too)

 **Expected behavior**
Keep all CE extension names 20 characters or less.

 **To Reproduce**
Any event produced will have this header if I'm not mistaken.

 **Knative release version**
1.13

**Comment by Cali0707** [comment]
Thanks for catching this @cchayka-campsci ! I'll add a fix here, but would you mind also opening an issue to the NodeJS library as well? Since this requirement is only a `SHOULD` in the spec, they should accept values without throwing an error if the length is wrong IMO. 

Since this will change behaviour for users (including those who originally requested this feature) we will need to discuss whether or not this fix gets backported or if we just use the new extension going forwards (i.e. 1.15+)

cc @matzew @pierDipi for whether we should backport this or not

**Comment by Cali0707** [comment]
Hey @cchayka-campsci I opened a PR to the node SDK and the new release (8.0.2) includes a fix for the bug you were encountering. I'm not sure if we will be changing the names of the extensions as that is a breaking change for our users
